# ConfigMap for non-sensitive app configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # AI Backend Configuration
  AI_BACKEND_PORT: "89"
  AI_USE_MOCK_DATA: "false"
  
  # Chat Backend Configuration
  CHAT_BACKEND_PORT: "88"
  
  # Frontend URLs
  CHAT_FRONTEND_PORT: "90"
  AI_FRONTEND_PORT: "91"
  APP_URL: "http://localhost"
  
  # CMS Configuration
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "sqlite"
  
  # Storage Container Settings
  STORAGE_CONTAINER: "face-detection"
---
# MongoDB PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# AI Backend PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-backend-claim0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Content PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-content
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Resources PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-resources
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-password
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
# Chat Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: default
  labels:
    app: chat-backend
spec:
  replicas: 5  # According to requirements, chat backend needs 5 replicas
  selector:
    matchLabels:
      app: chat-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: localhost:5000/chat-backend:latest
          ports:
            - containerPort: 88
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CHAT_BACKEND_PORT
            # Set MongoDB connection string with credentials from secret
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/chat?authSource=admin
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-password
---
# Chat Backend Service
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: default
spec:
  ports:
    - port: 88
      targetPort: 88
  selector:
    app: chat-backend
---
# Chat Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: default
  labels:
    app: chat-frontend
spec:
  replicas: 1  # According to requirements, chat frontend needs 1 replica
  selector:
    matchLabels:
      app: chat-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: localhost:5000/chat-frontend:latest
          ports:
            - containerPort: 90
---
# Chat Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: default
spec:
  ports:
    - port: 90
      targetPort: 90
  selector:
    app: chat-frontend
---
# AI Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
  namespace: default
  labels:
    app: ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
        - name: ai-backend
          image: localhost:5000/ai-backend:latest
          ports:
            - containerPort: 89
          env:
            # ConfigMap values
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AI_BACKEND_PORT
            - name: USE_MOCK_DATA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AI_USE_MOCK_DATA
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STORAGE_CONTAINER
            
            # Secret values
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: storage-connection-string
            - name: FACE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: face-api-key
            - name: FACE_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: face-api-endpoint
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-user
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-server
            - name: SQL_DB
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-db
          volumeMounts:
            - mountPath: /app/temp
              name: ai-backend-temp
      volumes:
        - name: ai-backend-temp
          persistentVolumeClaim:
            claimName: ai-backend-claim0
---
# AI Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-backend
  namespace: default
spec:
  ports:
    - port: 89
      targetPort: 89
  selector:
    app: ai-backend
---
# AI Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  namespace: default
  labels:
    app: ai-frontend
spec:
  replicas: 1  # According to requirements, AI frontend needs 1 replica
  selector:
    matchLabels:
      app: ai-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
        - name: ai-frontend
          image: localhost:5000/ai-frontend:latest
          ports:
            - containerPort: 91
          env:
            - name: REACT_APP_API_URL
              value: http://ai-backend:89
---
# AI Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
  namespace: default
spec:
  ports:
    - port: 91
      targetPort: 91
  selector:
    app: ai-frontend
---
# Statamic Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statamic
  namespace: default
  labels:
    app: statamic
spec:
  replicas: 2  # According to requirements, statamic needs 2 replicas
  selector:
    matchLabels:
      app: statamic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: statamic
    spec:
      containers:
        - name: statamic
          image: localhost:5000/statamic:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_DEBUG
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_URL
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_CONNECTION
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: statamic-credentials
                  key: app-key
          volumeMounts:
            - mountPath: /var/www/html/storage
              name: statamic-storage
            - mountPath: /var/www/html/content
              name: statamic-content
            - mountPath: /var/www/html/resources
              name: statamic-resources
      volumes:
        - name: statamic-storage
          persistentVolumeClaim:
            claimName: statamic-storage
        - name: statamic-content
          persistentVolumeClaim:
            claimName: statamic-content
        - name: statamic-resources
          persistentVolumeClaim:
            claimName: statamic-resources
---
# Statamic Service
apiVersion: v1
kind: Service
metadata:
  name: statamic
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: statamic
---
# Ingress to expose services externally
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: statamic
            port:
              number: 80
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: chat-frontend
            port:
              number: 90
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: chat-backend
            port:
              number: 88
      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: ai-frontend
            port:
              number: 91
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ai-backend
            port:
              number: 89