---
# ConfigMap for non-sensitive app configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  AI_BACKEND_PORT: "89"
  AI_USE_MOCK_DATA: "false"
  CHAT_BACKEND_PORT: "88"
  CHAT_FRONTEND_PORT: "90"
  AI_FRONTEND_PORT: "91"
  APP_URL: "http://localhost"  # Change to your domain/IP if needed
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "sqlite"
  STORAGE_CONTAINER: "face-images"  # Made consistent with secret value
---
# MongoDB PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# AI Backend PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-backend-claim0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Content PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-content
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Resources PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-resources
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Statamic Database PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statamic-database
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: microk8s-hostpath
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-password
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
# Chat Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: default
  labels:
    app: chat-backend
spec:
  replicas: 5  # As specified in the requirements
  selector:
    matchLabels:
      app: chat-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: raulbuontempo/chat-backend:latest
          ports:
            - containerPort: 88
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CHAT_BACKEND_PORT
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/chat?authSource=admin
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-password
---
# Chat Backend Service
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: default
spec:
  ports:
    - port: 88
      targetPort: 88
  selector:
    app: chat-backend
---
# Chat Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: default
  labels:
    app: chat-frontend
spec:
  replicas: 1  # As specified in the requirements
  selector:
    matchLabels:
      app: chat-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: raulbuontempo/chat-frontend:latest
          ports:
            - containerPort: 90
---
# Chat Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 90
      targetPort: 90
  selector:
    app: chat-frontend
---
# AI Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
  namespace: default
  labels:
    app: ai-backend
spec:
  replicas: 1  # As specified in the requirements
  selector:
    matchLabels:
      app: ai-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
        - name: ai-backend
          image: raulbuontempo/ai-backend:latest
          ports:
            - containerPort: 89
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AI_BACKEND_PORT
            - name: USE_MOCK_DATA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AI_USE_MOCK_DATA
            - name: STORAGE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: storage_container  # Using the key from secret
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: storage-connection-string
            - name: FACE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: face-api-key
            - name: FACE_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: face-api-endpoint
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-user
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-server
            - name: SQL_DB
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: sql-db
          volumeMounts:
            - mountPath: /app/temp
              name: ai-backend-claim0
      volumes:
        - name: ai-backend-claim0
          persistentVolumeClaim:
            claimName: ai-backend-claim0
---
# AI Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-backend
  namespace: default
spec:
  ports:
    - port: 89
      targetPort: 89
  selector:
    app: ai-backend
---
# AI Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  namespace: default
  labels:
    app: ai-frontend
spec:
  replicas: 1  # As specified in the requirements
  selector:
    matchLabels:
      app: ai-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
        - name: ai-frontend
          image: raulbuontempo/ai-frontend:latest
          ports:
            - containerPort: 91
          env:
            - name: REACT_APP_API_URL
              value: http://ai-backend:89
---
# AI Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
  namespace: default
spec:
  ports:
    - port: 91
      targetPort: 91
  selector:
    app: ai-frontend
---
# Statamic Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statamic
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statamic
  template:
    metadata:
      labels:
        app: statamic
    spec:
      # First, use an init container to properly set up directories
      initContainers:
      - name: init-directories
        image: localhost:5000/statamic:latest
        command: ['sh', '-c']
        args:
        - |
          # Create required cache directories
          mkdir -p /var/www/html/bootstrap/cache
          mkdir -p /var/www/html/storage/framework/views
          mkdir -p /var/www/html/storage/framework/cache
          mkdir -p /var/www/html/storage/framework/sessions
          mkdir -p /var/www/html/storage/app/public
          mkdir -p /var/www/html/database
          
          # Create SQLite database
          touch /var/www/html/database/database.sqlite
          
          # Create a simple .env file with required settings
          cat > /var/www/html/.env << EOF
          APP_NAME=Statamic
          APP_ENV=production
          APP_KEY=$(cat /run/secrets/statamic-app-key)
          APP_DEBUG=false
          APP_URL=http://localhost
          
          DB_CONNECTION=sqlite
          DB_DATABASE=/var/www/html/database/database.sqlite
          
          CACHE_DRIVER=file
          SESSION_DRIVER=file
          QUEUE_DRIVER=sync
          EOF
          
          # Set proper permissions
          chmod -R 777 /var/www/html/bootstrap/cache
          chmod -R 777 /var/www/html/storage
          chmod -R 777 /var/www/html/database
        volumeMounts:
        - name: statamic-storage
          mountPath: /var/www/html/storage
        - name: bootstrap-cache
          mountPath: /var/www/html/bootstrap/cache
        - name: statamic-database
          mountPath: /var/www/html/database
      
      # Then set up Statamic and copy templates
      - name: setup-statamic
        image: localhost:5000/statamic:latest
        command: ['sh', '-c']
        args:
        - |
          # Create resources directory structure
          mkdir -p /var/www/html/resources/views/errors
          
          # Copy templates
          cp /templates/layout.antlers.html /var/www/html/resources/views/
          cp /templates/home.antlers.html /var/www/html/resources/views/
          cp /templates/default.antlers.html /var/www/html/resources/views/
          cp /templates/errors/404.antlers.html /var/www/html/resources/views/errors/
          
          # Initialize Statamic
          cd /var/www/html
          php artisan storage:link
          php artisan statamic:install --no-interaction
          
          # Create default content
          mkdir -p /var/www/html/content/collections/pages
          
          # Create default home page
          echo -e "---\ntitle: Home\nid: home\ntemplate: home\n---\n# Welcome to Our Platform" > /var/www/html/content/collections/pages/home.md
          
          # Clear caches
          php artisan config:clear
          php artisan cache:clear
          
          # Set permissions again to be safe
          chmod -R 777 /var/www/html/bootstrap/cache
          chmod -R 777 /var/www/html/storage
          chmod -R 777 /var/www/html/content
          chmod -R 777 /var/www/html/resources
        volumeMounts:
        - name: statamic-storage
          mountPath: /var/www/html/storage
        - name: statamic-content
          mountPath: /var/www/html/content
        - name: statamic-resources
          mountPath: /var/www/html/resources
        - name: bootstrap-cache
          mountPath: /var/www/html/bootstrap/cache
        - name: statamic-database
          mountPath: /var/www/html/database
        - name: templates-volume
          mountPath: /templates
      
      # Main container
      containers:
      - name: statamic
        image: localhost:5000/statamic:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_URL
          value: "http://localhost"
        - name: DB_CONNECTION
          value: "sqlite"
        volumeMounts:
        - name: statamic-storage
          mountPath: /var/www/html/storage
        - name: statamic-content
          mountPath: /var/www/html/content
        - name: statamic-resources
          mountPath: /var/www/html/resources
        - name: bootstrap-cache
          mountPath: /var/www/html/bootstrap/cache
        - name: statamic-database
          mountPath: /var/www/html/database
      
      volumes:
      - name: statamic-storage
        persistentVolumeClaim:
          claimName: statamic-storage
      - name: statamic-content
        persistentVolumeClaim:
          claimName: statamic-content
      - name: statamic-resources
        persistentVolumeClaim:
          claimName: statamic-resources
      - name: bootstrap-cache
        emptyDir: {}  # Use an emptyDir for cache - doesn't need to persist
      - name: statamic-database
        persistentVolumeClaim:
          claimName: statamic-database  # Add this PVC if not already defined
      - name: templates-volume
        hostPath:
          path: /home/student/statamic-templates
          type: Directory
---
# Statamic Service
apiVersion: v1
kind: Service
metadata:
  name: statamic
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: statamic
---
# Ingress to expose services externally
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"  # Increase max upload size for AI component
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: statamic
            port:
              number: 80
      - path: /chat(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-frontend
            port:
              number: 90
      - path: /ws(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-backend
            port:
              number: 88
      - path: /ai(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ai-frontend
            port:
              number: 91
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ai-backend
            port:
              number: 89