apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # AI Backend Configuration
  AI_BACKEND_PORT: "89"
  AI_USE_MOCK_DATA: "false"
  
  # Chat Backend Configuration
  CHAT_BACKEND_PORT: "88"
  
  # Frontend URLs
  CHAT_FRONTEND_PORT: "90"
  AI_FRONTEND_PORT: "91"
  APP_URL: "http://localhost"
  
  # CMS Configuration
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "sqlite"
  
  # Storage Container Settings
  STORAGE_CONTAINER: "face-detection"