apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
stringData:
  storage-connection-string: "DefaultEndpointsProtocol=https;AccountName=stdstorage;AccountKey=/yPQ8eIvAFEdHcDMHFapgxf9CSLHUcpHMauFe3r6q+1wMCCkh8XOPxAhBifSEJjbHObeWcStf563+AStZnfnSA==;EndpointSuffix=core.windows.net"
  storage_container: "face-images"
  face-api-key: "AmxuyunYlzflJk85Pllr7fcYWtmcnJl1wl3DkyaCS7JOLlD5jcAEJQQJ99BDACGhslBXJ3w3AAAKACOG5xia"
  face-api-endpoint: "https://std-face-detection.cognitiveservices.azure.com/"
  sql-user: "sqladmin"
  sql-password: "5623288538953232Ra."
  sql-server: "std-sql-server.database.windows.net"
  sql-db: "face-detection-database"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  mongodb-root-username: "root"
  mongodb-root-password: "example"
  mongodb-uri: "mongodb://root:example@mongodb:27017/chat?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: statamic-credentials
type: Opaque
stringData:
  app-key: "base64:OhnkcxLhoN5uBZ2QjikXVT3pM/YC5kpyWl65hyCeNr8="