version: '3.8'

services:
  # Backend pentru Face Detection
  ai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-backend
    restart: unless-stopped
    environment:
      - PORT=89
      - USE_MOCK_DATA=false
    ports:
      - "89:89"
    volumes:
      - ./backend/temp:/app/temp
    networks:
      - ai-network

  # Frontend pentru Face Detection
  ai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:89
    ports:
      - "91:91"
    networks:
      - ai-network
    depends_on:
      - ai-backend

networks:
  ai-network:
    driver: bridge