apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: ai-backend
  name: ai-backend
  namespace: default
spec:
  ports:
    - name: "89"
      port: 89
      targetPort: 89
  selector:
    io.kompose.service: ai-backend
status:
  loadBalancer: {}
