apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: ai-frontend
  name: ai-frontend
  namespace: default
spec:
  ports:
    - name: "91"
      port: 91
      targetPort: 91
  selector:
    io.kompose.service: ai-frontend
status:
  loadBalancer: {}
