apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: ai-frontend
  name: ai-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/std-app-network: "true"
        io.kompose.service: ai-frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://localhost:89
          image: localhost:5000/ai-frontend:latest
          name: ai-frontend
          ports:
            - containerPort: 91
              hostPort: 91
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
