apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-backend
  name: chat-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/std-app-network: "true"
        io.kompose.service: chat-backend
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/chat?authSource=admin
            - name: PORT
              value: "88"
          image: localhost:5000/chat-backend:latest
          name: chat-backend
          ports:
            - containerPort: 88
              hostPort: 88
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
