apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-backend
  name: chat-backend
  namespace: default
spec:
  ports:
    - name: "88"
      port: 88
      targetPort: 88
  selector:
    io.kompose.service: chat-backend
status:
  loadBalancer: {}
