apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-frontend
  name: chat-frontend
  namespace: default
spec:
  ports:
    - name: "90"
      port: 90
      targetPort: 90
  selector:
    io.kompose.service: chat-frontend
status:
  loadBalancer: {}
