apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-frontend
  name: chat-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/std-app-network: "true"
        io.kompose.service: chat-frontend
    spec:
      containers:
        - image: localhost:5000/chat-frontend:latest
          name: chat-frontend
          ports:
            - containerPort: 90
              hostPort: 90
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
