apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: statamic
  name: statamic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statamic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/std-default: "true"
        io.kompose.service: statamic
    spec:
      containers:
        - env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_ENV
              value: local
            - name: APP_KEY
              value: placeholder
            - name: APP_URL
              value: http://localhost
            - name: DB_CONNECTION
              value: sqlite
          image: localhost:5000/statamic:latest
          name: statamic
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/storage
              name: statamic-storage
            - mountPath: /var/www/html/content
              name: statamic-content
            - mountPath: /var/www/html/resources
              name: statamic-resources
      restartPolicy: Always
      volumes:
        - name: statamic-storage
          persistentVolumeClaim:
            claimName: statamic-storage
        - name: statamic-content
          persistentVolumeClaim:
            claimName: statamic-content
        - name: statamic-resources
          persistentVolumeClaim:
            claimName: statamic-resources
status: {}
